name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v1
        with:
          ghc-version: '9.6.7'
      - run: cabal build --enable-tests
      - run: cabal test   