name: CI
on:
  push:
    paths:
      - '.github/**'
      - 'stack.yaml'
      - 'src/**'
      - 'test/**'
      - 'lambdachain.cabal'
  pull_request:
    paths:
      - '.github/**'
      - 'stack.yaml'
      - 'src/**'
      - 'test/**'
      - 'lambdachain.cabal'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.7'
          cabal-version: '3.14.2.0'
          enable-stack: true
          stack-version: '3.7.1'
      - run: cabal update
      - run: cabal build --enable-tests
      - run: cabal test