name: Haskell CI
on:
  workflow_run:
    workflows: ["OSV Scanner"]
    types: [completed]
  push:
    paths:
      - ".github/**"
      - "stack.yaml"
      - "src/**"
      - "test/**"
      - "lambdachain.cabal"
  pull_request:
    paths:
      - ".github/**"
      - "stack.yaml"
      - "src/**"
      - "test/**"
      - "lambdachain.cabal"
jobs:
  build:
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      # Binary keys should be Base64 encoded in GitHub Secrets
      ZKP_SIGNING_KEY: ${{ secrets.ZKP_SIGNING_KEY_B64 }}
      HASH_SALT: ${{ secrets.HASH_SALT_B64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fix timestamp issues
      - name: Set up Haskell environment
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: "9.6.7"
          cabal-version: "3.14.2.0"
          enable-stack: true
          stack-version: "3.7.1"
      - run: cabal freeze  # Generate consistent dependency plan
      - name: Cache Cabal store and dist
        uses: actions/cache@v3 # stores files temporarily (up to 7 days if unused) and reuses them across runs.
        with:
          path: |
            ${{ steps.setup.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-9.6.7-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-ghc-9.6.7-cabal-
      - run: cabal update
      - run: cabal build --enable-tests
      - run: cabal test
