name: Deploy to Production
on:
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "stack.yaml"
      - "src/**"
      - "test/**"
      - "lambdachain.cabal"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        run: echo "Deployment to production"  # for now
