name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  actions: read   # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  security-events: write   # Require writing security events to upload SARIF file to security tab
  contents: read  # to fetch code (actions/checkout)

jobs:
  osv-scan-hs:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.3
    with:
      scan-args: |-
        --recursive
        --lockfile=stack.yaml.lock
        .
  osv-scan-hs-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.3
    with:
      scan-args: |-
        --recursive
        --lockfile=stack.yaml.lock
        .
  check-scan-statuses:
    runs-on: ubuntu-latest
    needs:
      - osv-scan-hs
      - osv-scan-hs-pr
    # Always runs
    if: always()
    steps:
      - name: Evaluate previous scan statuses
        run: |
          if [[ ${{ contains(needs.*.result, 'failure') }} == "true" ]]; then
            echo "Failing scan status as a previous scan has failed"
            exit 1
          else
            echo "All good!"
            exit 0
          fi
